# Generated by Django 4.1 on 2024-04-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('tax_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('main_category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('uuId', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=200)),
                ('barcodes', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('tax_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_location', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.DecimalField(decimal_places=5, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=5, max_digits=8)),
                ('commission_rate', models.DecimalField(decimal_places=5, max_digits=8)),
                ('price', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('product_infos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_infos', to='mysalesweb.product')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('house_nr', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=200)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='mysalesweb.customer')),
                ('providers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='mysalesweb.provider')),
            ],
        ),
    ]
