# Generated by Django 4.0.6 on 2024-04-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysalesweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='isactive',
        ),
    ]
