"""Added ProdcutionInfo model

Revision ID: 6fb4827fd07c
Revises: 
Create Date: 2024-03-25 01:18:17.308499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb4827fd07c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('StoreLocation', sa.String(), nullable=True),
    sa.Column('Discount', sa.Float(), nullable=True),
    sa.Column('Tax', sa.Float(), nullable=True),
    sa.Column('CommissionRate', sa.Float(), nullable=True),
    sa.Column('ImgPath', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('DataCreated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductInfo')
    # ### end Alembic commands ###
