"""Added Prodcution model

Revision ID: eafc9d12f5e3
Revises: 
Create Date: 2024-03-25 16:51:36.933918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafc9d12f5e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Street', sa.String(), nullable=False),
    sa.Column('HouseNr', sa.String(), nullable=False),
    sa.Column('Province', sa.String(), nullable=False),
    sa.Column('Country', sa.String(), nullable=False),
    sa.Column('PostCode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(), nullable=False),
    sa.Column('MainCategory', sa.String(), nullable=False),
    sa.Column('SubCategory', sa.String(), nullable=False),
    sa.Column('UuID', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Phone', sa.String(), nullable=False),
    sa.Column('TaxNumber', sa.String(), nullable=False),
    sa.Column('Address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Address_id'], ['Address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProductInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('StoreLocation', sa.String(), nullable=False),
    sa.Column('Discount', sa.Float(), nullable=False),
    sa.Column('Tax', sa.Float(), nullable=False),
    sa.Column('CommissionRate', sa.Float(), nullable=False),
    sa.Column('ImgPath', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('DataCreated', sa.DateTime(), nullable=False),
    sa.Column('ProductId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ProductId'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Phone', sa.String(), nullable=False),
    sa.Column('TaxNumber', sa.String(), nullable=False),
    sa.Column('Address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Address_id'], ['Address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Provider')
    op.drop_table('ProductInfo')
    op.drop_table('Customer')
    op.drop_table('Product')
    op.drop_table('Address')
    # ### end Alembic commands ###
